### ISSUE TITLE
Issue Running Pre-Built Binary on 10.9.5

### ISSUE THREAD

**Issue by Sav0ia** [inolen/redream#71]
Thanks everyone for reading :) 
I found redream and decided to try it. 

On my initial run I **sudo** ran the redream unix with arguments to path of boot and flash files( As instructed). I was met with this ...

 `Failed to parse profiles/ps4.ini
Initializing VMU at /Users/ME/.redream/vmu.bin
Initializing flash rom from /Users/ME/Downloads/redream.x86_64-darwin-HEAD/dc_flash.bin
pvr_reconfigure_spg mode VGA, pixel_clock 13500000, line_clock 15734, vcount 262, hcount 857, interlace 0, vbstart 260, vbend 336
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/ME/Downloads/redream.x86_64-darwin-HEAD/redream
  Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/ME/Downloads/redream.x86_64-darwin-HEAD/redream
  Expected in: /usr/lib/libSystem.B.dylib`

I then decided to try again only running the the redream unix (as the bios and flash are now set) with **sudo** and received this 

`Loading controller profile profiles/ps4.ini
Failed to parse profiles/ps4.ini
Failed to load boot rom`

I then tried again **without the sudo** and received this

`Loading controller profile profiles/ps4.ini
Failed to parse profiles/ps4.ini
Failed to create shared memory object
[/Users/travis/build/inolen/redream/src/hw/memory.c:205] Check failed: unmap_shared_memory(memory->shmem, memory->shmem_base, memory->shmem_size)`

I've tried multiple times and have yielded the same result.  Sadly my compiling attempts have also been in error (possibly due to some dependencies I'm lacking so I'm grabbing them at the moment).

If anyone can help that would be great :) Thanks!

**Comment by inolen** [comment]
Running with sudo and then again without sudo may cause issues with file permissions for sure.

You shouldn't need to run with sudo at all, I'd empty out your `/Users/ME/.redream` directory and run again without sudo, passing the correct boot / flash parameters.

**Comment by Sav0ia** [comment]
Dear Inolen, 

Thanks for your reply!

I just tried the process again without sudo,  For the initial run with boot/flash parameters I received this error again

`Loading controller profile profiles/ps4.ini
Failed to parse profiles/ps4.ini
Initializing VMU at /Users/ME/.redream/vmu.bin
Initializing flash rom from /Users/ME/Downloads/redream.x86_64-darwin-HEAD/dc_flash.bin
pvr_reconfigure_spg mode VGA, pixel_clock 13500000, line_clock 15734, vcount 262, hcount 857, interlace 0, vbstart 260, vbend 336
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/ME/Downloads/redream.x86_64-darwin-HEAD/redream
  Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/ME/Downloads/redream.x86_64-darwin-HEAD/redream
  Expected in: /usr/lib/libSystem.B.dylib
Trace/BPT trap: 5
`

And for the second run once all is in .redream I receive this

`Loading controller profile profiles/ps4.ini
Failed to parse profiles/ps4.ini
Failed to load boot rom`


Same errors seem to be popping up :(

Thanks for your help!

**Comment by inolen** [comment]
I believe the issue here is that I compile the pre-built binaries with a much newer version of OSX (it's using Xcode 8.2 which I think is El Capitan / macOS) and I haven't done any testing with compiling binaries which are backwards compatible with older OSX versions.

It _looks_ like I may just need to set https://cmake.org/cmake/help/v3.0/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html in https://github.com/inolen/redream/blob/master/.travis.yml, but I don't have a mac running an older version of OSX to test with right now.

Your best bet will probably be to compile the code on your own if you'd like to tinker around, but be warned, the project isn't very user-friendly just yet.

**Comment by Sav0ia** [comment]
Thanks again Inolen!

Oh I see, if it's an easy set perhaps that could solve the issue :)

Also I just tried to compile(9th time trying) as per instructions on the site to see if that would work but was met with this error...

`Scanning dependencies of target libsoundio_static
[  0%] Building C object deps/libsoundio/CMakeFiles/libsoundio_static.dir/src/soundio.c.o
In file included from /Users/ME/redream/deps/libsoundio/src/soundio.c:8:
In file included from /Users/ME/redream/deps/libsoundio/src/soundio_private.h:28:
In file included from /Users/ME/redream/deps/libsoundio/src/coreaudio.h:14:
/Users/ME/redream/deps/libsoundio/src/atomics.h:44:10: fatal error: 
      'stdatomic.h' file not found
#include <stdatomic.h>
         ^
1 error generated.
make[2]: *** [deps/libsoundio/CMakeFiles/libsoundio_static.dir/src/soundio.c.o] Error 1
make[1]: *** [deps/libsoundio/CMakeFiles/libsoundio_static.dir/all] Error 2
make: *** [all] Error 2`

Last time it got to 16% and died, this time much less.  Really not sure what I'm doing wrong :/
But I did notice during the cmake process a lot of files were not found even though the git copy was successful.

Thanks again!

**Comment by inolen** [comment]
Ah, `stdatomic.h` missing error is due to the older version of Xcode used by Mavericks.

Upgrading to El Capitan / macOS would probably resolve the issue.

**Comment by Sav0ia** [comment]
Yeah I'm on Xcode 6.1- I'll try 6.2 ( The maximum for Mavericks) and see will document what happens~ 

Thanks again!

**Comment by Sav0ia** [comment]
Update: After updating to 6.2 I'm still getting the same error. So a newer version of Xcode is required, therefore updating Mavericks is also required.

Info for anyone having the same issue : **Redream does not currently run on Mavericks**

Appreciate all the help inolen, will try Redream again upon updating :)
